#!/usr/bin/env bash

# set -e

DOTFILES="${HOME}"/dotfiles

shopt -s dotglob

for folder in "${DOTFILES}"/*; do
  if [ -d ${folder} ] && [ "$(basename "${folder}")" != "." ] && [ "$(basename "${folder}")" != ".." ] && [ "$(basename "${folder}")" != ".git" ] ; then
    echo "==== $(basename $folder) ===="
    stow -d "${DOTFILES}" -t "${HOME}" --adopt --restow  --no-folding  --verbose=1 $(basename $folder) 
    echo "Directory $(basename $folder) stowed."
  fi
done

# for file in "${DOTFILES}"/.*; do
#   if [ -f ${file} ] && [ "$(basename "${file}")" != "." ] && [ "$(basename "${file}")" != ".." ]; then
#     filename=$(basename $file)
#     echo "==== ${filename} ===="
#     stow  -d "${DOTFILES}" --adopt --verbose=1 "${filename#.}"
#     echo "File ${filename} stowed."
#   fi
# done
