#!/usr/bin/env bash

set -e

DOTFILES="${HOME}"/dotfiles

for folder in "${DOTFILES}"/*; do
  if [ -d ${folder} ] && [ "$(basename "${folder}")" != "." ] && [ "$(basename "${folder}")" != ".." ] && [ "$(basename "${folder}")" != ".git" ] ; then
    echo "==== $(basename $folder) ===="
    stow -d "${DOTFILES}" -t "${HOME}" --adopt --restow  --no-folding  --verbose=1 $(basename $folder) 
    echo "Directory $(basename $folder) stowed."
  fi
done
