[[mgr.prepend_keymap]]
on   = [ "s", "h" ]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on   = [ "s", "f" ]
run = 'search fd'
desc = "Search files by name using fd"

[[mgr.prepend_keymap]]
on   = [ "s", "r" ]
run = 'search rg'
desc = "Search fies by content using ripgrep"

[[mgr.prepend_keymap]]
on   = [ "q", "r" ]
# run = 'shell "qmv -f do" --block'
run = [ "shell \"qmv -f do && clear\" --block", "refresh" ]
desc = "Interactive rename inside folder"

# Small remaps to make q r combo work
[[mgr.prepend_keymap]]
on = [ "q", "d" ]
run = "quit"
desc = "Exit and CMD here" 

[[mgr.prepend_keymap]]
on = [ "q", "q" ]
run = "quit --no-cwd-file"
desc = "Exit without CMD here"

# LazyGit plugin
[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

# DuckDB plugin
[[mgr.prepend_keymap]]
on = "H"
run = "plugin duckdb -1"
desc = "Scroll one column to the left"

[[mgr.prepend_keymap]]
on = "L"
run = "plugin duckdb +1"
desc = "Scroll one column to the right"

[[mgr.prepend_keymap]]
on = ["g", "o"]
run = "plugin duckdb -open"
desc = "open with duckdb"

[[mgr.prepend_keymap]]
on = ["g", "u"]
run = "plugin duckdb -ui"
desc = "open with duckdb ui"

# keymap.toml
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

# keymap.toml
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
