
[[manager.prepend_keymap]]
on   = [ "s", "h" ]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = [ "s", "f" ]
run = 'search fd'
desc = "Search files by name using fd"

[[manager.prepend_keymap]]
on   = [ "s", "r" ]
run = 'search rg'
desc = "Search fies by content using ripgrep"

[[manager.prepend_keymap]]
on   = [ "q", "r" ]
run = 'shell "qmv -f do" --block'
desc = "Interactive rename inside folder"

# Small remaps to make q r combo work
[[manager.prepend_keymap]]
on = [ "q", "d" ]
run = "quit"
desc = "Exit and CMD here" 

[[manager.prepend_keymap]]
on = [ "q", "q" ]
run = "quit --no-cwd-file"
desc = "Exit without CMD here"
